"""add role to users

Revision ID: 333a7a3fc9d9
Revises: d3c626fca582
Create Date: 2026-04-25 09:58:08.347512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333a7a3fc9d9'
down_revision = 'd3c626fca582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.alter_column('product_name_snapshot',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('unit_snapshot',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               existing_nullable=False)

    # Add role as nullable first, backfill existing users as superadmin, then enforce NOT NULL.
    op.add_column('users', sa.Column('role', sa.String(length=32), nullable=True))
    op.execute("UPDATE users SET role = 'superadmin'")
    op.alter_column('users', 'role', nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('role')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.alter_column('unit_snapshot',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('product_name_snapshot',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
